#!/bin/sh
#
# by Erik Osheim
#
# This script just helps automate the process of dumping trees. It's still a
# bit tricky to see the exact structure, but this is still really helpful.

# which phase's results should be inspected?
#PHASE="parser"
PHASE="kind-projector"

# where is the plugin located?
PLUGIN="target/scala-2.9.2/kind-projector_2.9.2-0.3.jar"

scalac \
    -Xprint:$PHASE \
    -Yshow-trees \
    -Ycompact-trees \
    -Ystop-after:$PHASE \
    -Xplugin:$PLUGIN \
    "$@"
